### ISSUE TITLE
Failed to configure tokenizer

### ISSUE THREAD

**Issue by lspliner** [deNULL/Az.js#3]
`var Az = require("az");`
`var tokens = Az.Tokens();`
`tokens.append(input, {});`
`tokens = tokens.done();`

This code throws exception on line 3:
`config = config ? Az.extend(this.config, config) : this.config;`
`ReferenceError: Az is not defined`

**Comment by andrey-pavlenko** [comment]
Добрый день.

linux, node v9.11.1

Такой код **(без config)** работает:
```javascript
const Az = require('az');
const tokens = Az.Tokens('Мама мыла раму').done(['SPACE'], true));
```

Такой код **(Tokens вызывается с config)**:
```javascript
const Az = require('az');
const tokens = Az.Tokens('Мама <b>мыла</b> раму', { html: true })
  .done(['SPACE'], true)
);
```
Ошибка:
```
/home/node_modules/az/dist/az.js:1700
        this.config = config ? Az.extend(defaults, config) : defaults;
                               ^

ReferenceError: Az is not defined
    at new Tokens (/home/node_modules/az/dist/az.js:1700:32)
    at Object.Tokens (/home/node_modules/az/dist/az.js:1707:14)
    at Object.<anonymous> (/home/src/message.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
```
